feat: publish pcre-7.1

diff --git a/RunTest b/RunTest
--- a/RunTest
+++ b/RunTest
@@ -1,19 +1,32 @@
 #! /bin/sh
 
-# This file is generated by configure from RunTest.in. Make any changes
-# to that file.
-
 # Run PCRE tests
 
-cf=diff
+cf="diff -u"
 valgrind=
-if [ ! -d testdata ] ; then
-  ln -s @top_srcdir@/testdata testdata
+testdata=testdata
+
+if [ -n "$srcdir" -a -d "$srcdir" ] ; then
+  testdata="$srcdir/testdata"
 fi
-testdata=./testdata
 
+# Find which optional facilities are available
 
-# Select which tests to run; if no selection, run all
+case `./pcretest -C | ./pcregrep 'Internal link size'` in
+  *2) link_size=2;;
+  *3) link_size=3;;
+  *4) link_size=4;;
+   *) echo "Failed to find internal link size"; exit 1;;
+esac
+
+./pcretest -C | ./pcregrep 'No UTF-8 support' >/dev/null
+utf8=$?
+
+./pcretest -C | ./pcregrep 'No Unicode properties support' >/dev/null
+ucp=$?
+
+# Select which tests to run; for those that are explicitly requested, check
+# that the necessary optional facilities are available.
 
 do1=no
 do2=no
@@ -36,13 +49,13 @@ while [ $# -gt 0 ] ; do
     7) do7=yes;;
     8) do8=yes;;
     9) do9=yes;;
-    valgrind) valgrind="valgrind -q";; 
+    valgrind) valgrind="valgrind -q";;
     *) echo "Unknown test number $1"; exit 1;;
   esac
   shift
 done
 
-if [ "@LINK_SIZE@" != "" -a "@LINK_SIZE@" != "-DLINK_SIZE=2" ] ; then
+if [ "$link_size" != "2" ] ; then
   if [ $do2 = yes ] ; then
     echo "Can't run test 2 with an internal link size other than 2"
     exit 1
@@ -57,7 +70,7 @@ if [ "@LINK_SIZE@" != "" -a "@LINK_SIZE@" != "-DLINK_SIZE=2" ] ; then
   fi
 fi
 
-if [ "@UTF8@" = "" ] ; then
+if [ $utf8 -eq 0 ] ; then
   if [ $do4 = yes ] ; then
     echo "Can't run test 4 because UTF-8 support is not configured"
     exit 1
@@ -80,7 +93,7 @@ if [ "@UTF8@" = "" ] ; then
   fi
 fi
 
-if [ "@UCP@" = "" ] ; then
+if [ $ucp -eq 0 ] ; then
   if [ $do6 = yes ] ; then
     echo "Can't run test 6 because Unicode property support is not configured"
     exit 1
@@ -91,22 +104,26 @@ if [ "@UCP@" = "" ] ; then
   fi
 fi
 
+# If no specific tests were requested, select all that are relevant.
+
 if [ $do1 = no -a $do2 = no -a $do3 = no -a $do4 = no -a \
      $do5 = no -a $do6 = no -a $do7 = no -a $do8 = no -a \
      $do9 = no ] ; then
   do1=yes
   do2=yes
   do3=yes
-  if [ "@UTF8@" != "" ] ; then do4=yes; fi
-  if [ "@UTF8@" != "" ] ; then do5=yes; fi
-  if [ "@UTF8@" != "" -a "@UCP@" != "" ] ; then do6=yes; fi
-  do7=yes 
-  if [ "@UTF8@" != "" ] ; then do8=yes; fi
-  if [ "@UTF8@" != "" -a "@UCP@" != "" ] ; then do9=yes; fi
+  if [ $utf8 -ne 0 ] ; then do4=yes; fi
+  if [ $utf8 -ne 0 ] ; then do5=yes; fi
+  if [ $utf8 -ne 0 -a $ucp -ne 0 ] ; then do6=yes; fi
+  do7=yes
+  if [ $utf8 -ne 0 ] ; then do8=yes; fi
+  if [ $utf8 -ne 0 -a $ucp -ne 0 ] ; then do9=yes; fi
 fi
 
 # Show which release
 
+echo ""
+echo PCRE C library tests
 ./pcretest /dev/null
 
 # Primary test, Perl-compatible
@@ -120,13 +137,12 @@ if [ $do1 = yes ] ; then
   else exit 1
   fi
   echo "OK"
-  echo " "
 fi
 
 # PCRE tests that are not Perl-compatible - API & error tests, mostly
 
 if [ $do2 = yes ] ; then
-  if [ "@LINK_SIZE@" = "" -o "@LINK_SIZE@" = "-DLINK_SIZE=2" ] ; then
+  if [ "$link_size" = "2" ] ; then
     echo "Test 2: API and error handling (not Perl compatible)"
     $valgrind ./pcretest -q $testdata/testinput2 testtry
     if [ $? = 0 ] ; then
@@ -135,14 +151,15 @@ if [ $do2 = yes ] ; then
     else exit 1
     fi
     echo "OK"
-    echo " "
   else
-    echo Test 2 skipped for link size other than 2 \(@LINK_SIZE@\)
-    echo " " 
+    echo Test 2 skipped for link size other than 2 \($link_size\)
+    echo " "
   fi
 fi
 
-# Locale-specific tests, provided the "fr_FR" locale is available
+# Locale-specific tests, provided the "fr_FR" locale is available.
+# TODO: Try the locale name "french" instead - as used on Windows - but
+# this will mean modifying the input and output data.
 
 if [ $do3 = yes ] ; then
   locale -a | grep '^fr_FR$' >/dev/null
@@ -159,7 +176,6 @@ if [ $do3 = yes ] ; then
       else
       echo "OK"
       fi
-      echo " "
     else exit 1
     fi
   else
@@ -180,11 +196,10 @@ if [ $do4 = yes ] ; then
   else exit 1
   fi
   echo "OK"
-  echo " "
 fi
 
 if [ $do5 = yes ] ; then
-  if [ "@LINK_SIZE@" = "" -o "@LINK_SIZE@" = "-DLINK_SIZE=2" ] ; then
+  if [ "$link_size" = "2" ] ; then
     echo "Test 5: API and internals for UTF-8 support (not Perl compatible)"
     $valgrind ./pcretest -q $testdata/testinput5 testtry
     if [ $? = 0 ] ; then
@@ -193,15 +208,14 @@ if [ $do5 = yes ] ; then
     else exit 1
     fi
     echo "OK"
-    echo " "
   else
-    echo Test 5 skipped for link size other than 2 \(@LINK_SIZE@\)
-    echo " " 
+    echo Test 5 skipped for link size other than 2 \($link_size\)
+    echo " "
   fi
 fi
 
 if [ $do6 = yes ] ; then
-  if [ "@LINK_SIZE@" = "" -o "@LINK_SIZE@" = "-DLINK_SIZE=2" ] ; then
+  if [ "$link_size" = "2" ] ; then
     echo "Test 6: Unicode property support"
     $valgrind ./pcretest -q $testdata/testinput6 testtry
     if [ $? = 0 ] ; then
@@ -210,10 +224,9 @@ if [ $do6 = yes ] ; then
     else exit 1
     fi
     echo "OK"
-    echo " "
   else
-    echo Test 6 skipped for link size other than 2 \(@LINK_SIZE@\)
-    echo " " 
+    echo Test 6 skipped for link size other than 2 \($link_size\)
+    echo " "
   fi
 fi
 
@@ -228,7 +241,6 @@ if [ $do7 = yes ] ; then
   else exit 1
   fi
   echo "OK"
-  echo " "
 fi
 
 if [ $do8 = yes ] ; then
@@ -240,7 +252,6 @@ if [ $do8 = yes ] ; then
   else exit 1
   fi
   echo "OK"
-  echo " "
 fi
 
 if [ $do9 = yes ] ; then
@@ -252,7 +263,6 @@ if [ $do9 = yes ] ; then
   else exit 1
   fi
   echo "OK"
-  echo " "
 fi
 
 # End
